import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import NativeExtensionsProvider from '~/components/providers/native-extensions-provider';
import ThemeProvider from '~/components/providers/theme-provider';
import { Toaster } from '~/components/ui/sonner';
import { cn } from '~/lib/utils';

import '~/lib/utils/string-extensions';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang="en" className="dark" style={{ colorScheme: 'dark' }}>
            <body className={cn(inter.className, 'flex flex-col min-h-svh antialiased')}>
                <NativeExtensionsProvider>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                        <Toaster richColors />
                        {children}
                    </ThemeProvider>
                </NativeExtensionsProvider>
            </body>
        </html>
    );
};

export default RootLayout;
