version: '3.8'

services:
    typesense:
        image: typesense/typesense:${TYPESENSE_VERSION:-latest}
        restart: on-failure
        ports:
            - ${TYPESENSE_PORT}:8108
        volumes:
            - ./typesense-data:/data
        command: '--data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors'
